#!/bin/sh

set -eu

repo_root=$(git rev-parse --show-toplevel)
cd "$repo_root"
target_path="$repo_root/.githooks"

configured_path=$(git config --local --get core.hooksPath || true)
case "$configured_path" in
  ''|.githooks|"$target_path") ;;
  *)
    echo "Goalrail hook setup blocked: core.hooksPath is already $configured_path" >&2
    exit 1
    ;;
esac

if test -z "$configured_path"; then
  legacy_hooks=$(git rev-parse --git-path hooks)
  for legacy_hook in "$legacy_hooks"/*; do
    test -f "$legacy_hook" && test -x "$legacy_hook" || continue
    case "$legacy_hook" in
      *.sample) continue ;;
    esac
    if grep -q 'generated by prek' "$legacy_hook"; then
      continue
    fi
    if test "$(basename "$legacy_hook")" = "pre-push" &&
      grep -q 'Goalrail' "$legacy_hook"; then
      continue
    fi
    echo "Goalrail hook setup blocked: existing executable hook would be disabled: $legacy_hook" >&2
    exit 1
  done
fi

git config --local core.hooksPath "$target_path"
echo "Installed Goalrail hooks from $target_path"
